// withIosDeploymentTarget — 把所有 CocoaPods 目标的 iOS 部署目标统一抬到指定版本。
//
// 为什么需要它：
//   Xcode 27 把最低部署目标抬到 iOS 15.0，并且从「警告」变成了「硬错误」。
//   而不少第三方 Pod 的 podspec 里仍写着 12.x / 13.x：
//     - react-native-svg      12.4（最新的 15.15.5 也没改）
//     - async-storage         13.4（最新的 3.1.1 是 13.0，依旧 <15）
//     - ReachabilitySwift     12.0（expo-updates 从 CocoaPods trunk 拉的，版本不受 package.json 控制）
//   所以「升级依赖」解决不了，必须在构建时覆盖。这些库的代码本身在 iOS 16 上没有问题，
//   改的只是一句元数据声明。
//
// 为什么做成 config plugin 而不是直接改 ios/Podfile：
//   ios/ 是 prebuild 生成的（且在 .gitignore 里），手改会被下次 prebuild 冲掉，
//   EAS 云端构建更是每次都从头生成。写成插件才能本地和 EAS 都稳。

const { withDangerousMod } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

const MARKER = '# @generated by withIosDeploymentTarget';

// Podfile 末尾的固定结构：post_install 的 end，再加 target 块的 end。
// 插在这里是为了跑在 react_native_post_install 之后——它也会动部署目标，
// 我们必须最后写才能生效。
const CLOSING = '\n  end\nend';

function buildSnippet(deploymentTarget) {
  return [
    `    ${MARKER}`,
    `    # 详见 plugins/withIosDeploymentTarget.js 的说明`,
    `    installer.pods_project.targets.each do |target|`,
    `      target.build_configurations.each do |build_configuration|`,
    `        build_configuration.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '${deploymentTarget}'`,
    `      end`,
    `    end`,
  ].join('\n');
}

const withIosDeploymentTarget = (config, { deploymentTarget = '16.4' } = {}) => {
  return withDangerousMod(config, [
    'ios',
    (cfg) => {
      const podfilePath = path.join(cfg.modRequest.platformProjectRoot, 'Podfile');
      const contents = fs.readFileSync(podfilePath, 'utf8');

      // 幂等：prebuild 可能在同一个 ios/ 上跑多次
      if (contents.includes(MARKER)) return cfg;

      const idx = contents.lastIndexOf(CLOSING);
      if (idx === -1) {
        // 宁可炸掉 prebuild，也不要静默跳过——静默跳过的话
        // 报错会推迟到 xcodebuild 阶段，那时候更难查。
        throw new Error(
          '[withIosDeploymentTarget] 没能在 Podfile 里定位到 post_install 块的结尾。' +
            'Expo 可能改了 Podfile 模板，需要更新这个插件的锚点。',
        );
      }

      const next =
        contents.slice(0, idx) + '\n' + buildSnippet(deploymentTarget) + contents.slice(idx);
      fs.writeFileSync(podfilePath, next);

      return cfg;
    },
  ]);
};

module.exports = withIosDeploymentTarget;
